// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eefyrfictceaxwqnbuar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlZnlyZmljdGNlYXh3cW5idWFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNzM4NjgsImV4cCI6MjA2NDk0OTg2OH0.IQsDKtfbrsKi15t831CmbpVVGI4Cg7vDbVdF671HWDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);